### ISSUE TITLE
Remove Emails

### ISSUE THREAD

**Issue by vaanshu** [rix4uni/email-inventory#2]
remove emails of cnbctv18.com

Best Regards
Vansh

**Comment by rix4uni** [comment]
This file has been deleted:
- https://github.com/rix4uni/email-inventory/blob/2b5cc250a2543e4a81a799da5907cf9573ab8d03/Emails/cnbctv18.com.txt

**Comment by rix4uni** [comment]
**Your mention file has been deleted and also added to .gitignore they will not commit again:**
- https://github.com/rix4uni/email-inventory/blob/main/Emails/cnbctv18.com.txt

**Check .gitignore**
- https://github.com/rix4uni/email-inventory/blob/main/.gitignore

Please close this issue if you don't have any other request.
