### ISSUE TITLE
Remove Amdocs email ids from the email inventory.

### ISSUE THREAD

**Issue by maheshwaghmode** [rix4uni/email-inventory#3]
Please help to remove Amdocs email ids listed in the email inventory.

- https://github.com/rix4uni/email-inventory:Emails/
- https://github.com/rix4uni/email-inventory:Emails/amdocs.com.txt

**Comment by rix4uni** [comment]
Removed:
- https://github.com/rix4uni/email-inventory/blob/main/Emails/amdocs.com.txt

**Comment by maheshwaghmode** [comment]
Thank you!
