### ISSUE TITLE
Removal of company emails.

### ISSUE THREAD

**Issue by Watson-cmd** [rix4uni/email-inventory#32]
Hey,
Can these below emails please be removed from the repository as they are abrdn company emails. Thanks

**If you found email releated to you or your company and you don't want to show them publicly, Please add name of those email files you want to remove**
e.g, just change the filename placeholder
- https://github.com/rix4uni/email-inventory/blob/main/Emails/abrdn.txt 
- https://github.com/rix4uni/email-inventory/blob/main/Emails/aberdeen-asset.com.txt

**Comment by rix4uni** [comment]
https://github.com/rix4uni/email-inventory/issues/33
