### ISSUE TITLE
Remove Veepee corporate emails

### ISSUE THREAD

**Issue by vpsec** [rix4uni/email-inventory#40]
Hello rix4uni,

I'm writing on behalf of Veepee Cybersecurity Team with our GitHub shared account.

While performing some scans, we found some corporate employees emails available publicly on your GitHub.
This drastically increases our public exposure and could lead to targeted phishing campaigns

Would you please remove the below txt file from your email-inventory repository?

https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/veepee.com.txt

Thanks in advance for your help!
Veepee Cybersecurity Team

**Comment by rix4uni** [comment]
- https://github.com/rix4uni/email-inventory/issues/41

**Comment by vpsec** [comment]
Hello rix4uni,

Thanks for your quick action!

We found additional emails:

- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/veepee.fr.txt
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/privalia.com.txt
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/vente-privee.com.txt
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/adotmob.com.txt

If you could also please remove them, that would be greatly appreciated!

Thanks in advance for your help!
Veepee Cybersecurity Team

**Comment by vpsec** [comment]
Tell me if you prefer having separate individual issue for each link or if one issue is fine for you :) 

Thanks
