### ISSUE TITLE
Remove additional Veepee corporate emails

### ISSUE THREAD

**Issue by vpsec** [rix4uni/email-inventory#43]
Hello rix4uni,

We found additional emails:
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/veepee.fr.txt
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/privalia.com.txt
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/vente-privee.com.txt
- https://github.com/rix4uni/email-inventory/blob/2b3c825b640972449360ff0becc3fe81451239cf/Emails/adotmob.com.txt

If you could also please remove them, that would be greatly appreciated!

Thanks in advance for your help!
Veepee Cybersecurity Team

**Comment by rix4uni** [comment]
- https://github.com/rix4uni/email-inventory/issues/44
- https://github.com/rix4uni/email-inventory/issues/45
- https://github.com/rix4uni/email-inventory/issues/46
- https://github.com/rix4uni/email-inventory/issues/47
