### ISSUE TITLE
Removal of atkinsglobal emails

### ISSUE THREAD

**Issue by FlareBarrett** [rix4uni/email-inventory#48]
We are contacting about the following emails to ask for removal please:
jean.yu@atkinsglobal.com
raymundo.castro@atkinsglobal.com
douglas.smith@atkinsglobal.com
tim.over@atkinsglobal.com
vesselstudy@atkinsglobal.com
janet.luce@atkinsglobal.com
emily.doe@atkinsglobal.com

Found at email-inventory/Emails/atkinsglobal.com.txt

**Comment by rix4uni** [comment]
- https://github.com/rix4uni/email-inventory/issues/49
