### ISSUE TITLE
Removal of atkinsglobal emails

### ISSUE THREAD

**Issue by rix4uni** [rix4uni/email-inventory#49]
**If you found email releated to you or your company and you don't want to show them publicly, Please add name of those email files you want to remove**
e.g, just change the filename placeholder
- https://github.com/rix4uni/email-inventory/blob/main/Emails/atkinsglobal.com.txt

**Comment by kinan-Q** [comment]
Please remove all references to Al Baraka Bank Syria domains and email addresses from your repository, including:

M.Lahham@albarakasyria.com
H.Sibai@albarakasyria.com
F.Khorfan@albarakasyria.com
B.Shbib@albarakasyria.com
Y.Esaied@albarakasyria.com
M.Qaderi@albarakasyria.com
Additionally, refrain from including any Al Baraka Syria email domains or addresses in any future repositories or commits. This is unauthorized and violates privacy regulation

**Comment by kinan-Q** [comment]
albarakasyria.com.txt

https://github.com/rix4uni/email-inventory/blob/1ad994df909fc4ad2b890760cba6a4e6777e6230/Emails/albarakasyria.com.txt
