### ISSUE TITLE
Remove list (email)

### ISSUE THREAD

**Issue by kolobchanskij** [rix4uni/email-inventory#5]
Remove list:
ziganshinaeju@akbars.ru
igor.bulakhov@akbars.ru
tatyana.saveleva@akbars.ru
75kanc@akbars.ru
ekaterina.larionova.nik@akbars.ru
fraud@akbars.ru
vasilevang@akbars.ru

**Comment by rix4uni** [comment]
Deleted:
- https://github.com/rix4uni/email-inventory/blob/main/Emails/akbars.ru.txt
