### ISSUE TITLE
remove Emails

### ISSUE THREAD

**Issue by bmstu1** [rix4uni/email-inventory#51]
Remove please Emails/ivi.ru.txt file

**Comment by rix4uni** [comment]
Are you sure this file even exist in this repo because i couldn't find.

**Comment by bmstu1** [comment]
https://github.com/rix4uni/email-inventory/blob/1e5d55e56f56eaa6cb79218292ee3430e3cba40e/Emails/ivi.ru.txt

Please check if you delete histiry in repo

**Comment by rix4uni** [comment]
Can you please tell me where do you get this commit id `1e5d55e56f56eaa6cb79218292ee3430e3cba40e` because this commit id exist in github database not in the repo

![image](https://github.com/user-attachments/assets/1df66d3c-ae9b-4f8b-8b11-335d3337f20d)
